# Generated by Django 3.2.6 on 2021-08-29 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_method',
            new_name='payment_method',
        ),
    ]
